require "user"
require "user.utils.plugin.keymap"
require "user.utils.plugin.autopairs"
require "user.utils.plugin.identline"
require "user.utils.plugin.lualine"
require "user.utils.plugin.nvim-tree"
require "user.utils.plugin.project"
require "user.utils.plugin.surround"
require "user.utils.plugin.toggleterm"
require "user.utils.plugin.treesitter"

